spring:
  application:
    name: Nobi
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:sqlite:nobi.db
    driver-class-name: org.sqlite.JDBC


telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

openai:
  base-url: https://api.openai.com/v1
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini

storage:
  download-dir: downloads
  output-dir: output