

spring:
  application:
    name: Nobi
  config:
      import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:sqlite:nobi.db
    driver-class-name: org.sqlite.JDBC


telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

